### ISSUE TITLE
NAPI C++ test fail for HDF4 and XML

### ISSUE THREAD

**Issue by eugenwintersberger** [nexusformat/code#426] opened 2016-05-19 10:08 UTC
It seems that after some changes to the attribute interface the tests for C++ fail with HDF4 and XML.
For HDF4 I get the following error message

```
wintersb@haso228w1:$ ./napi_test_cpp-hdf4 
NXinquirefile found: napi_test_cpp.hdf
This is a HDF4 file, attribute array API is not supported here 
terminate called after throwing an instance of 'NeXus::Exception'
  what():  NXgetnextattr failed
Aborted
```

and for XML

```
wintersb@haso228w1:$ ./napi_test_cpp-xml 
NXinquirefile found: napi_test_cpp.xml
This is an XML file, attribute array API is not supported here 
terminate called after throwing an instance of 'NeXus::Exception'
  what():  NXgetnextattr failed
Aborted
```

I guess this should be easy to fix for those people who made the changes to the attribute interface. 
Please, when you make changes in the code, always ensure that all tests are green.

**Comment by zjttoefs** [comment] 2016-05-19 10:10
This is not really fixable and hence the desired, expected behaviour.

Tobias

________________________________

**Comment by eugenwintersberger** [comment] 2016-05-19 10:12
Ok - in this case I will change the test accordingly.

**Comment by zjttoefs** [comment] 2016-05-19 11:25
Sorry, my mistake.

**Comment by zjttoefs** [comment] 2016-05-19 11:28
I thought the test was trying to read or write attribute arrays in backends where that isn't possible. Reading attributes in well formed file should still work using the legacy attribute API.

I don't understand why that is a problem in C++ but not in C. Maybe there lies the answer.

**Comment by zjttoefs** [comment] 2016-05-19 11:34
It does indeed and someone didn't update the message for the exception.

But I should be able to fix that. Good we have the test. Thanks for raising that Eugen!

**Comment by zjttoefs** [comment] 2016-05-19 14:09
@eugenwintersberger could you include the test in the "make test" procedure?

**Comment by eugenwintersberger** [comment] 2016-05-19 14:25
Actually they are all in the ``test`` target of make. I used the call of the individual test to show the error message which is not shown when using `make test`.

**Comment by zjttoefs** [comment] 2016-05-19 14:59
You are absolutely correct! Once I enable stuff like hdf4 and c++ it "automatically" appears.
We would not be here if the computer could guess what we are trying to do, so I cannot complain.

Nice work, thanks!

**Comment by zjttoefs** [comment] 2016-05-19 15:16
So the problem is that with just the experience of HDF5 people expect NXgetnextattra at al to work.
But for XML/HDF4 files that's not the case.

NXgetnextattra could be calling the "old" attribute API under the hood. But the NXgetattra is too different and NXputattra is near impossible to do.

Do we need to fall back to the original API? Can you tell what kind of file is open from the NAPI?

**Comment by zjttoefs** [comment] 2016-06-14 14:20
No discussion needed at this point. I know what to do.

**Comment by quantumsteve** [comment] 2016-08-05 18:39
This issue is currently blocking Mantid from working with NeXus v4.4

**Comment by stuartcampbell** [comment] 2020-05-27 18:17
Is this still a problem.  The mantid issue that was tracking this claims it was fixed. 
 https://github.com/mantidproject/mantid/issues/17001#issuecomment-253523131

**Comment by quantumsteve** [comment] 2020-05-27 19:00
Mantid has been using v4.4.3 for several years. We're happy to see this issue closed.

**Comment by stuartcampbell** [comment] 2020-05-27 20:50
Thanks @quantumsteve - I will close it now, anyone please reopen if needed.

**Closed by stuartcampbell** 2020-05-27 20:50 UTC
Labels: c++ bindings
