### ISSUE TITLE
NeXus API cannot handle HDF5 VL string data type

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/code#329] opened 2014-05-06 03:08 UTC
**Original reporter**: *[FreddieAkeroyd](https://github.com/FreddieAkeroyd)*

**Comment by rayosborn** [comment] 2016-04-20 16:58
Since the nexpy/nexusformat module writes variable-length strings by default (see nexusformat/python-nxs#10), this is a serious issue. Does anyone have any ideas how to fix this in the API? I know people want to put the API into minimal maintenance mode, but while people are using it, this is a serious bug.

**Comment by zjttoefs** [comment] 2016-04-20 17:02
I've not seen evidence of it and have no example file. That would be a start. Was requested 2 years ago.

**Comment by rayosborn** [comment] 2016-04-20 17:06
Jens Krueger has provided one in the linked pull request (nexusformat/python-nxs#10). The nexus.zip file contains a file, `mynexus_nexusformat.nxs` which cannot be read by the NAPI, but is perfectly valid HDF5. Actually, anything written using the nexpy/nexusformat module that includes a string field would show this problem. Since I haven't used the C API in years, I didn't know this was a problem until just now.

**Comment by prjemian** [comment] 2016-04-20 17:07
Look at the zip file from this comment
https://github.com/nexusformat/python-nxs/pull/10#issuecomment-212448727

In that zip file, look at file *mynexus_nexusformat.nxs*

**Comment by mkoennecke** [comment] 2016-04-21 07:21
I can confirm that VL strings were never supported in the C-NAPI. And no one put out a requirement for them. Now, with the python API writing these beasts by default we are compelled to support this. I may look into this once the SINQ startup is done with. And no one else finds time to look into this beforehand.

**Comment by rayosborn** [comment] 2016-04-21 14:20
It's not just Python. The need to support this is an inevitable consequence of encouraging people to write NeXus files using the HDF5 library directly. People are going to use whatever features of HDF5 seem most convenient, and variable-length strings are definitely one of them, unless you refuse to allow users to ever edit a string field in a NeXus file.

**Comment by prjemian** [comment] 2016-04-21 14:25
For now, I will add comment about this to the NeXus manual.

**Comment by FreddieAkeroyd** [comment] 2016-04-21 22:00
There was some work done on supporting the reading of VL strings back in 2012 via d3be17f4da3c8f70e96d086aaeeb57289e702086 and 7de1b96c9acc812e6a375e193f2634c66479edf6 and I think it was working for an example provided at that time, but maybe that wasn't the whole story...

**Comment by zjttoefs** [comment] 2016-04-26 15:13
During Teclo: We think this is important but not urgent. Mark will have a look after the SINQ startup.

**Comment by mkoennecke** [comment] 2016-05-06 09:56
I got down to looking into this earlier then expected. 

First, there are ways to write strings properly to NeXus files using h5py:

dset.attrs["name"] = numpy.string_("Hello")

or

dset = f.create_dataset("string_ds", (100,), dtype="S10")

will work out of the box. 

Second, the bug was in NXgetinfo64. The function failed to determine the length of the variable 
length string. Which caused insufficient memory to be allocated and yada, yada. Possibly this is 
even a bug in HDF5. Now the code is reading the vl string and determines the length through 
strlen(). This seems to work.  Now the library can read the supplied example file which caused the problem. 

More tests would be good. 

I committed the fix in branch issue-329 . We will have to decide if this is good enough.

**Comment by rayosborn** [comment] 2016-05-06 12:43
Thanks, Mark. That's great progress. 

I'm not sure I understood why you mentioned h5py. The problem was not that NeXpy couldn't create fixed-length strings; that's available now if you use:

    >>>  a = NXfield('text', dtype='S4')

However, your example will not work in Python 3 if you use Unicode.

    >>> f.create_dataset('unicode_text', shape=(10,), dtype='S10')
    >>> f['unicode_text'][()]='café'
    TypeError: No conversion path for dtype: dtype('<U4')

For that, you have to use the special object datatype that h5py defines.

    h5.special_dtype(vlen=str) (Python 3) or h5.special_dtype(vlen=unicode) (Python 2)

Supporting Unicode is one of the strongest reasons for needing to support variable-length strings. Hopefully, you've fixed that now, for reading files at least.

**Comment by rayosborn** [comment] 2016-05-06 12:46
To clarify my last comment, you can store fixed-length strings in Python 3 as well, but you have to encode them as byte strings first. That would cause problems on reading, because, unless we insist on a particular encoding, such as UTF-8, we won't have a clue what encoding was used in writing the file. The object datatype that h5py uses ensures that the string is stored as UTF-8.

**Comment by mkoennecke** [comment] 2016-05-06 12:58
Ray,


Am 06.05.2016 um 14:46 schrieb Ray Osborn <notifications@github.com<mailto:notifications@github.com>>:


To clarify my last comment, you can store fixed-length strings in Python 3 as well, but you have to encode them as byte strings first. That would cause problems on reading, because, unless we insist on a particular encoding, such as UTF-8, we won't have a clue what encoding was used in writing the file. The object datatype that h5py uses ensures that the string is stored as UTF-8.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub<https://github.com/nexusformat/code/issues/329#issuecomment-217429775>

can you please provide a python 3 generated file with unicode strings? Such that I can check that this now works as expected.

Regards,

    Mark

**Comment by rayosborn** [comment] 2016-05-06 14:12
Here's one. It reads fine in Python 3, although ironically, I have found a bug reading it in nexusformat v0.3 on Python 2.7, which I will fix as soon as possible.
[test.nxs.zip](https://github.com/nexusformat/code/files/252371/test.nxs.zip)

**Comment by mkoennecke** [comment] 2016-05-06 14:38
Ray,

Am 06.05.2016 um 16:12 schrieb Ray Osborn <notifications@github.com<mailto:notifications@github.com>>:


Here's one. It reads fine in Python 3, although ironically, I have found a bug reading it in nexusformat v0.3 on Python 2.7, which I will fix as soon as possible.
test.nxs.zip<https://github.com/nexusformat/code/files/252371/test.nxs.zip>

Thanks. There is still something subtle wrong. I will have to look into this next week.

Regards,

Mark

**Comment by mkoennecke** [comment] 2016-05-09 12:02
Hi,

I think I got it now. It was the variable length attributes which caused the problem. This is now fixed with the last commit on issue-329.  I think we briefly discuss this on tomorrows telco and close this for the time being. Until another example file turns up which breaks it.

**Comment by rayosborn** [comment] 2016-05-09 13:34
Mark,
This is a slightly expanded version of the test file I uploaded last week. It includes both fields and attributes of fixed and variable length.

Here's the tree:

    root:NXroot
      @HDF5_Version = '1.8.15'
      @file_name = 'test.nxs'
      @file_time = '2016-05-06T09:07:01.635543'
      @h5py_version = '2.5.0'
      @nexusformat_version = '0.3.0'
      entry:NXentry
        byte_text = 'café'
          @units = 'café'
        unicode_text = 'café'
          @units = 'café'

The dtypes of byte_text (both field and attribute) are 'S10', while those of unicode_text are the special object datatype that h5py defines to produce UTF-8 encoded variable-length strings. My default encoding is also UTF-8, so the fixed-length strings should return the same values.

Now, I need to get some coffee.
 
[test.nxs.zip](https://github.com/nexusformat/code/files/255051/test.nxs.zip)

**Comment by mkoennecke** [comment] 2016-05-10 09:38
Ray,

Hope you enjoyed your coffee. Your extended test file passes with my latest version. Perhaps you should 
taken champagne rather then coffee :-)

**Comment by zjttoefs** [comment] 2016-05-10 14:51
Please merge.

**Comment by mkoennecke** [comment] 2016-05-10 15:40
Merged the branch with the fix to master

**Closed by mkoennecke** 2016-05-10 15:40 UTC
Labels: bug, napi
